name: ci

on:
  pull_request:
  push:
    branches: [main]

jobs:
  install:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - uses: ./install
        with:
          tool: cargo-component
          version: dev

      - uses: ./install
        with:
          tool: node
          version: 20.19.2
